# Generated by Django 4.0 on 2021-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
