# Generated by Django 4.0 on 2021-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'pasenger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasengerContentTypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('customer_pasenger', 'Global customer pasenger'), ('vendor_pasenger', 'Global vendor pasenger'), ('any_pasenger', 'Global any pasenger')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
